name: Android CI for SoftClick_mobile
run-name: ${{ github.actor }} opened/reopened a pull request to ${{ github.base_ref }} from ${{ github.head_ref }}
on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - main
      - develop
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: openjdk
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew assemble